---
 
- hosts: docker
  become: false
  tasks:

  - name: update docker containers in multimedia stack
    community.general.docker_compose:
      project_src: /docker/multimedia
      pull: yes
      build: no

  - name: update docker containers in bitwarden stack
    community.general.docker_compose:
      project_src: /docker/bitwarden
      pull: yes
      build: no

  - name: update docker containers in ubooquity stack
    community.general.docker_compose:
      project_src: /docker/ubooquity
      pull: yes
      build: no

  - name: update docker containers in tdarr stack
    community.general.docker_compose:
      project_src: /docker/tdarr
      pull: yes
      build: no

  - name: update docker containers in portainer stack
    community.general.docker_compose:
      project_src: /docker/portainer
      pull: yes
      build: no

  - name: update docker containers in duplicati stack
    community.general.docker_compose:
      project_src: /docker/duplicati
      pull: yes
      build: no

  - name: update docker containers in wikijs stack
    community.general.docker_compose:
      project_src: /docker/wikijs
      pull: yes
      build: no

  - name: Prune everything
    community.docker.docker_prune:
      containers: yes
      images: yes
      networks: yes
      volumes: yes
      builder_cache: yes
