---
 
- hosts: docker
  become: false
  tasks:

  - name: update docker containers in multimedia stack
    community.general.docker_compose:
      project_src: /mnt/docker/multimedia
      pull: yes
      build: no

  - name: update docker containers in bitwarden stack
    community.general.docker_compose:
      project_src: /mnt/docker/bitwarden
      pull: yes
      build: no

  - name: update docker containers in grafana stack
    community.general.docker_compose:
      project_src: /mnt/docker/grafana
      pull: yes
      build: no

  - name: update docker containers in openspeedtest stack
    community.general.docker_compose:
      project_src: /mnt/docker/openspeedtest
      pull: yes
      build: no

  - name: update docker containers in scrutiny stack
    community.general.docker_compose:
      project_src: /mnt/docker/scrutiny
      pull: yes
      build: no

  - name: update docker containers in telegraf stack
    community.general.docker_compose:
      project_src: /mnt/docker/telegraf
      pull: yes
      build: no

  - name: update docker containers in ubooquity stack
    community.general.docker_compose:
      project_src: /mnt/docker/ubooquity
      pull: yes
      build: no

  - name: update docker containers in unifi-controller stack
    community.general.docker_compose:
      project_src: /mnt/docker/unifi-controller
      pull: yes
      build: no

  - name: update docker containers in tdarr stack
    community.general.docker_compose:
      project_src: /mnt/docker/tdarr
      pull: yes
      build: no

  - name: update docker containers in portainer stack
    community.general.docker_compose:
      project_src: /mnt/docker/portainer
      pull: yes
      build: no

  - name: update docker containers in wikijs stack
    community.general.docker_compose:
      project_src: /mnt/docker/wikijs
      pull: yes
      build: no

  - name: Prune everything
    community.docker.docker_prune:
      containers: yes
      images: yes
      networks: yes
      volumes: yes
      builder_cache: yes
